# Generated by Django 5.2.1 on 2025-06-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products_images/default.jpg', upload_to='products_images/'),
        ),
    ]
